### ISSUE TITLE
升级到vite4.0后，sftp连接失败

### ISSUE THREAD

**Issue by JackieCheung** [han-neil/sftp-uploader#1]
```
$sftp-uploader
  - sftpError:> sftp连接失败Error: connect: getConnection: All configured authentication methods failed 
```

**Comment by han-neil** [comment]
你好，我这里本地试了是可以的，请排查下是否是网络配置的原因。
如还是无法连接，可提供最小复现代码给我排查。

**Comment by JackieCheung** [comment]
回复一下：密码是写在 `env` 文件中 `VITE_SERVER_PASSWORD=xxxxxxxxxx#`，`vite 4.0 env` 变量有调整，`#` 号符直接过滤了，需要加个双引号 `VITE_SERVER_PASSWORD="xxxxxxxxxx#"` 即可
